// Decompiled with JetBrains decompiler
// Type: QuestList_Item
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: BE2A90B7-A8AB-4E1F-A9DE-BBA047493101
// Assembly location: C:\r\The-Alchemist-Code-Story\res\Assembly-CSharp_japan_dmm.dll

using UnityEngine;
using UnityEngine.UI;

#nullable disable
[AddComponentMenu("UI/Drafts/QuestList_Item")]
public class QuestList_Item : UIDraft
{
  [UIDraft.AutoGenerated]
  public Image Clear;
  [UIDraft.AutoGenerated]
  public Text Text_QuestName;
  [UIDraft.AutoGenerated]
  public Text Text_PointNum;
  [UIDraft.AutoGenerated]
  public Text Text_Point;
}
