// Decompiled with JetBrains decompiler
// Type: SelectArea
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: BE2A90B7-A8AB-4E1F-A9DE-BBA047493101
// Assembly location: C:\r\The-Alchemist-Code-Story\res\Assembly-CSharp_japan_dmm.dll

using UnityEngine;
using UnityEngine.UI;

#nullable disable
[AddComponentMenu("UI/Drafts/SelectArea")]
public class SelectArea : UIDraft
{
  [UIDraft.AutoGenerated]
  public Text Text_AreaName;
  [UIDraft.AutoGenerated]
  public Text Text_MenuTitle;
  [UIDraft.AutoGenerated]
  public Button Area_Item;
  [UIDraft.AutoGenerated]
  public Button Btn_Decide;
  [UIDraft.AutoGenerated]
  public Button Btn_BackWorld;
}
