// Decompiled with JetBrains decompiler
// Type: Win_Btn_YN_Title_Flx
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: BE2A90B7-A8AB-4E1F-A9DE-BBA047493101
// Assembly location: C:\r\The-Alchemist-Code-Story\res\Assembly-CSharp_japan_dmm.dll

using UnityEngine;
using UnityEngine.Events;
using UnityEngine.UI;

#nullable disable
[AddComponentMenu("UI/Drafts/Win_Btn_YN_Title_Flx")]
public class Win_Btn_YN_Title_Flx : UIDraft
{
  [UIDraft.AutoGenerated]
  public Text Text_Title;
  [UIDraft.AutoGenerated]
  public Text Text_Message;
  [UIDraft.AutoGenerated]
  public Button Btn_No;
  [UIDraft.AutoGenerated]
  public Button Btn_Yes;
  public Text Txt_No;
  public Text Txt_Yes;
  public UIUtility.DialogResultEvent OnClickYes;
  public UIUtility.DialogResultEvent OnClickNo;

  private void OnWindowClose(UIWindow window)
  {
    Object.DestroyImmediate((Object) ((Component) ((Component) this).GetComponentInParent<Canvas>()).gameObject);
  }

  public void BeginClose()
  {
    UIUtility.PopCanvas(true);
    UIWindow component = ((Component) this).GetComponent<UIWindow>();
    component.OnWindowClose = new UIWindow.WindowEvent(this.OnWindowClose);
    component.Close();
  }

  private void OnClickButton(GameObject obj)
  {
    this.BeginClose();
    if (Object.op_Equality((Object) obj, (Object) ((Component) this.Btn_Yes).gameObject))
    {
      if (this.OnClickYes == null)
        return;
      this.OnClickYes(((Component) this).gameObject);
    }
    else
    {
      if (this.OnClickNo == null)
        return;
      this.OnClickNo(((Component) this).gameObject);
    }
  }

  private void Awake()
  {
    UIUtility.AddEventListener(((Component) this.Btn_Yes).gameObject, (UnityEvent) this.Btn_Yes.onClick, new UIUtility.EventListener(this.OnClickButton));
    UIUtility.AddEventListener(((Component) this.Btn_No).gameObject, (UnityEvent) this.Btn_No.onClick, new UIUtility.EventListener(this.OnClickButton));
  }
}
