// Decompiled with JetBrains decompiler
// Type: PlayerStatus
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 059BC2E0-629D-4929-B655-9E68C13AB758
// Assembly location: S:\Program Files (x86)\DMMGamePlayer\games\tagatame\tagatame_Data\Managed\Assembly-CSharp.dll

using UnityEngine;
using UnityEngine.UI;

[AddComponentMenu("UI/Drafts/PlayerStatus")]
public class PlayerStatus : UIDraft
{
  [UIDraft.AutoGenerated]
  public Text Text_PlayerName;
  [UIDraft.AutoGenerated]
  public Text Text_LevelNum;
  [UIDraft.AutoGenerated]
  public Text Text_Point_Current;
  [UIDraft.AutoGenerated]
  public Text Text_Point_Max;
  [UIDraft.AutoGenerated]
  public Text Text_Timer;
  [UIDraft.AutoGenerated]
  public Text Text_KakinItemNum;
  [UIDraft.AutoGenerated]
  public Text Text_GoldNum;
  [UIDraft.AutoGenerated]
  public Slider Gauge_EXP;
  [UIDraft.AutoGenerated]
  public Slider Gauge_Shutsugeki;
}
