// Decompiled with JetBrains decompiler
// Type: QuestList_Item
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 059BC2E0-629D-4929-B655-9E68C13AB758
// Assembly location: S:\Program Files (x86)\DMMGamePlayer\games\tagatame\tagatame_Data\Managed\Assembly-CSharp.dll

using UnityEngine;
using UnityEngine.UI;

[AddComponentMenu("UI/Drafts/QuestList_Item")]
public class QuestList_Item : UIDraft
{
  [UIDraft.AutoGenerated]
  public Image Clear;
  [UIDraft.AutoGenerated]
  public Text Text_QuestName;
  [UIDraft.AutoGenerated]
  public Text Text_PointNum;
  [UIDraft.AutoGenerated]
  public Text Text_Point;
}
