// Decompiled with JetBrains decompiler
// Type: SelectWorld
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 059BC2E0-629D-4929-B655-9E68C13AB758
// Assembly location: S:\Program Files (x86)\DMMGamePlayer\games\tagatame\tagatame_Data\Managed\Assembly-CSharp.dll

using UnityEngine;
using UnityEngine.UI;

[AddComponentMenu("UI/Drafts/SelectWorld")]
public class SelectWorld : UIDraft
{
  [UIDraft.AutoGenerated]
  public Button World_Item;
  [UIDraft.AutoGenerated]
  public Text Text_WorldName;
  [UIDraft.AutoGenerated]
  public Text Text_MenuTitle;
  [UIDraft.AutoGenerated]
  public Button Btn_Decide;
}
