// Decompiled with JetBrains decompiler
// Type: UIDraft
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 059BC2E0-629D-4929-B655-9E68C13AB758
// Assembly location: S:\Program Files (x86)\DMMGamePlayer\games\tagatame\tagatame_Data\Managed\Assembly-CSharp.dll

using System;
using UnityEngine;

public abstract class UIDraft : MonoBehaviour
{
  private void Start()
  {
    this.enabled = false;
  }

  public class AutoGenerated : Attribute
  {
  }

  public class ObsoleteHeader : PropertyAttribute
  {
    public readonly string header;

    public ObsoleteHeader(string header)
    {
      this.header = header;
    }
  }
}
