// Decompiled with JetBrains decompiler
// Type: PlayerStatus
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: BE2A90B7-A8AB-4E1F-A9DE-BBA047493101
// Assembly location: C:\r\The-Alchemist-Code-Story\res\Assembly-CSharp_japan_dmm.dll

using UnityEngine;
using UnityEngine.UI;

#nullable disable
[AddComponentMenu("UI/Drafts/PlayerStatus")]
public class PlayerStatus : UIDraft
{
  [UIDraft.AutoGenerated]
  public Text Text_PlayerName;
  [UIDraft.AutoGenerated]
  public Text Text_LevelNum;
  [UIDraft.AutoGenerated]
  public Text Text_Point_Current;
  [UIDraft.AutoGenerated]
  public Text Text_Point_Max;
  [UIDraft.AutoGenerated]
  public Text Text_Timer;
  [UIDraft.AutoGenerated]
  public Text Text_KakinItemNum;
  [UIDraft.AutoGenerated]
  public Text Text_GoldNum;
  [UIDraft.AutoGenerated]
  public Slider Gauge_EXP;
  [UIDraft.AutoGenerated]
  public Slider Gauge_Shutsugeki;
}
