// Decompiled with JetBrains decompiler
// Type: SelectWorld
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: BE2A90B7-A8AB-4E1F-A9DE-BBA047493101
// Assembly location: C:\r\The-Alchemist-Code-Story\res\Assembly-CSharp_japan_dmm.dll

using UnityEngine;
using UnityEngine.UI;

#nullable disable
[AddComponentMenu("UI/Drafts/SelectWorld")]
public class SelectWorld : UIDraft
{
  [UIDraft.AutoGenerated]
  public Button World_Item;
  [UIDraft.AutoGenerated]
  public Text Text_WorldName;
  [UIDraft.AutoGenerated]
  public Text Text_MenuTitle;
  [UIDraft.AutoGenerated]
  public Button Btn_Decide;
}
