// Decompiled with JetBrains decompiler
// Type: UIDraft
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: BE2A90B7-A8AB-4E1F-A9DE-BBA047493101
// Assembly location: C:\r\The-Alchemist-Code-Story\res\Assembly-CSharp_japan_dmm.dll

using System;
using UnityEngine;

#nullable disable
public abstract class UIDraft : MonoBehaviour
{
  private void Start() => ((Behaviour) this).enabled = false;

  public class AutoGenerated : Attribute
  {
  }

  public class ObsoleteHeader : PropertyAttribute
  {
    public readonly string header;

    public ObsoleteHeader(string header) => this.header = header;
  }
}
