// Decompiled with JetBrains decompiler
// Type: SRPG.BattleBonus
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: BE2A90B7-A8AB-4E1F-A9DE-BBA047493101
// Assembly location: C:\r\The-Alchemist-Code-Story\res\Assembly-CSharp_japan_dmm.dll

#nullable disable
namespace SRPG
{
  public enum BattleBonus
  {
    EffectRange,
    EffectScope,
    EffectHeight,
    HitRate,
    AvoidRate,
    CriticalRate,
    SlashAttack,
    PierceAttack,
    BlowAttack,
    ShotAttack,
    MagicAttack,
    ReactionAttack,
    JumpAttack,
    GainJewel,
    UsedJewelRate,
    ActionCount,
    GutsRate,
    AutoJewel,
    ChargeTimeRate,
    CastTimeRate,
    BuffTurn,
    DebuffTurn,
    CombinationRange,
    HpCostRate,
    SkillUseCount,
    PoisonDamage,
    PoisonTurn,
    Resist_Slash,
    Resist_Pierce,
    Resist_Blow,
    Resist_Shot,
    Resist_Magic,
    Resist_Reaction,
    Resist_Jump,
    Avoid_Slash,
    Avoid_Pierce,
    Avoid_Blow,
    Avoid_Shot,
    Avoid_Magic,
    Avoid_Reaction,
    Avoid_Jump,
    GainJewelRate,
    UsedJewel,
    UnitDefenseFire,
    UnitDefenseWater,
    UnitDefenseWind,
    UnitDefenseThunder,
    UnitDefenseShine,
    UnitDefenseDark,
    CriticalDamageRate,
    NoDivAttack,
    Resist_NoDiv,
    Avoid_NoDiv,
    Resist_BuffHpMax,
    Resist_BuffAtk,
    Resist_BuffDef,
    Resist_BuffMag,
    Resist_BuffMnd,
    Resist_BuffRec,
    Resist_BuffDex,
    Resist_BuffSpd,
    Resist_BuffCri,
    Resist_BuffLuk,
    Resist_BuffMov,
    Resist_BuffJmp,
    Resist_DebuffHpMax,
    Resist_DebuffAtk,
    Resist_DebuffDef,
    Resist_DebuffMag,
    Resist_DebuffMnd,
    Resist_DebuffRec,
    Resist_DebuffDex,
    Resist_DebuffSpd,
    Resist_DebuffCri,
    Resist_DebuffLuk,
    Resist_DebuffMov,
    Resist_DebuffJmp,
  }
}
