// Decompiled with JetBrains decompiler
// Type: SRPG.EMissionType
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 059BC2E0-629D-4929-B655-9E68C13AB758
// Assembly location: S:\Program Files (x86)\DMMGamePlayer\games\tagatame\tagatame_Data\Managed\Assembly-CSharp.dll

namespace SRPG
{
  public enum EMissionType
  {
    [QuestMissionType(QuestMissionValueType.ValueIsNone), TowerQuestMissionType(QuestMissionProgressJudgeType.NotSupport)] KillAllEnemy,
    [QuestMissionType(QuestMissionValueType.ValueIsNone), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] NoDeath,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.LessEqual)] LimitedTurn,
    [QuestMissionType(QuestMissionValueType.ValueIsInt)] ComboCount,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.LessEqual)] MaxSkillCount,
    [QuestMissionType(QuestMissionValueType.ValueIsInt)] MaxItemCount,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] MaxPartySize,
    [QuestMissionType(QuestMissionValueType.ValueIsEnumName), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] LimitedUnitElement,
    [QuestMissionType(QuestMissionValueType.ValueIsString), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] LimitedUnitID,
    [QuestMissionType(QuestMissionValueType.ValueIsNone)] NoMercenary,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.NotSupport)] Killstreak,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.LessEqual)] TotalHealHPMax,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.GreatorEqual)] TotalHealHPMin,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.LessEqual)] TotalDamagesTakenMax,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.GreatorEqual)] TotalDamagesTakenMin,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.LessEqual)] TotalDamagesMax,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.GreatorEqual)] TotalDamagesMin,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.NotSupport)] LimitedCT,
    [QuestMissionType(QuestMissionValueType.ValueIsInt)] LimitedContinue,
    [QuestMissionType(QuestMissionValueType.ValueIsNone)] NoNpcDeath,
    [QuestMissionType(QuestMissionValueType.ValueIsKeyAndIntValue), TowerQuestMissionType(QuestMissionProgressJudgeType.NotSupport)] TargetKillstreak,
    [QuestMissionType(QuestMissionValueType.ValueIsString)] NoTargetDeath,
    [QuestMissionType(QuestMissionValueType.ValueIsKeyAndIntValue), TowerQuestMissionType(QuestMissionProgressJudgeType.LessEqual)] BreakObjClashMax,
    [QuestMissionType(QuestMissionValueType.ValueIsKeyAndIntValue), TowerQuestMissionType(QuestMissionProgressJudgeType.GreatorEqual)] BreakObjClashMin,
    [QuestMissionType(QuestMissionValueType.ValueIsString)] WithdrawUnit,
    [QuestMissionType(QuestMissionValueType.ValueIsNone)] UseMercenary,
    [QuestMissionType(QuestMissionValueType.ValueIsString), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] LimitedUnitID_MainOnly,
    [QuestMissionType(QuestMissionValueType.ValueIsNone), TowerQuestMissionType(QuestMissionProgressJudgeType.NotSupport)] MissionAllCompleteAtOnce,
    [QuestMissionType(QuestMissionValueType.ValueIsStringArray), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] OnlyTargetArtifactType,
    [QuestMissionType(QuestMissionValueType.ValueIsStringArray), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] OnlyTargetArtifactType_MainOnly,
    [QuestMissionType(QuestMissionValueType.ValueIsStringArray), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] OnlyTargetJobs,
    [QuestMissionType(QuestMissionValueType.ValueIsStringArray), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] OnlyTargetJobs_MainOnly,
    [QuestMissionType(QuestMissionValueType.ValueIsString), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] OnlyTargetUnitBirthplace,
    [QuestMissionType(QuestMissionValueType.ValueIsString), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] OnlyTargetUnitBirthplace_MainOnly,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] OnlyTargetSex,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] OnlyTargetSex_MainOnly,
    [QuestMissionType(QuestMissionValueType.ValueIsNone), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] OnlyHeroUnit,
    [QuestMissionType(QuestMissionValueType.ValueIsNone), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] OnlyHeroUnit_MainOnly,
    [QuestMissionType(QuestMissionValueType.ValueIsString), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] Finisher,
    [QuestMissionType(QuestMissionValueType.ValueIsInt)] TotalGetTreasureCount,
    [QuestMissionType(QuestMissionValueType.ValueIsString)] KillstreakByUsingTargetItem,
    [QuestMissionType(QuestMissionValueType.ValueIsString)] KillstreakByUsingTargetSkill,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] MaxPartySize_IgnoreFriend,
    [QuestMissionType(QuestMissionValueType.ValueIsNone), TowerQuestMissionType(QuestMissionProgressJudgeType.EqualZero)] NoAutoMode,
    [QuestMissionType(QuestMissionValueType.ValueIsNone)] NoDeath_NoContinue,
    [QuestMissionType(QuestMissionValueType.ValueIsStringArray)] OnlyTargetUnits,
    [QuestMissionType(QuestMissionValueType.ValueIsStringArray)] OnlyTargetUnits_MainOnly,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.LessEqual)] LimitedTurn_Leader,
    [QuestMissionType(QuestMissionValueType.ValueIsStringArray)] NoDeathTargetNpcUnits,
    [QuestMissionType(QuestMissionValueType.ValueIsInt)] UseTargetSkill,
    [QuestMissionType(QuestMissionValueType.ValueIsInt)] TotalKillstreakCount,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.GreatorEqual)] TotalGetGemCount_Over,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.LessEqual)] TotalGetGemCount_Less,
    [QuestMissionType(QuestMissionValueType.ValueIsInt)] TeamPartySizeMax_IncMercenary,
    [QuestMissionType(QuestMissionValueType.ValueIsInt)] TeamPartySizeMax_NoMercenary,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.LessEqual)] ChallengeCountMax,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.LessEqual)] DeathCountMax,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.NotSupport)] DamageOver,
    [QuestMissionType(QuestMissionValueType.ValueIsStringArray), TowerQuestMissionType(QuestMissionProgressJudgeType.NotSupport)] SurviveUnit,
    [QuestMissionType(QuestMissionValueType.ValueIsKeyAndIntValue), TowerQuestMissionType(QuestMissionProgressJudgeType.NotSupport)] KillTargetEnemy,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.LessEqual)] TakenDamageLessEqual,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.GreatorEqual)] TakenDamageGreatorEqual,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.LessEqual)] LimitedTurnLessEqualPartyOnly,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.GreatorEqual)] LimitedTurnGreatorEqualPartyOnly,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.NotSupport)] KillEnemy,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.GreatorEqual)] BreakObj,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.LessEqual)] LimitedTurnLessEqualPartyAndNPC,
    [QuestMissionType(QuestMissionValueType.ValueIsInt), TowerQuestMissionType(QuestMissionProgressJudgeType.GreatorEqual)] LimitedTurnGreatorEqualPartyAndNPC,
  }
}
