// Decompiled with JetBrains decompiler
// Type: SRPG.JSON_MasterParam
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 059BC2E0-629D-4929-B655-9E68C13AB758
// Assembly location: S:\Program Files (x86)\DMMGamePlayer\games\tagatame\tagatame_Data\Managed\Assembly-CSharp.dll

namespace SRPG
{
  public class JSON_MasterParam
  {
    public JSON_FixParam[] Fix;
    public JSON_UnitParam[] Unit;
    public JSON_UnitJobOverwriteParam[] UnitJobOverwrite;
    public JSON_SkillParam[] Skill;
    public JSON_BuffEffectParam[] Buff;
    public JSON_CondEffectParam[] Cond;
    public JSON_AbilityParam[] Ability;
    public JSON_ItemParam[] Item;
    public JSON_ArtifactParam[] Artifact;
    public JSON_WeaponParam[] Weapon;
    public JSON_RecipeParam[] Recipe;
    public JSON_JobParam[] Job;
    public JSON_JobSetParam[] JobSet;
    public JSON_EvaluationParam[] Evaluation;
    public JSON_AIParam[] AI;
    public JSON_GeoParam[] Geo;
    public JSON_RarityParam[] Rarity;
    public JSON_ShopParam[] Shop;
    public int[] AbilityRank;
    public int[] UnitLvTbl;
    public int[] PlayerLvTbl;
    public int[] ArtifactLvTbl;
    public int[] AwakePieceTbl;
    public JSON_PlayerParam[] Player;
    public JSON_GrowParam[] Grow;
    public JSON_LocalNotificationParam[] LocalNotification;
    public JSON_TrophyCategoryParam[] TrophyCategory;
    public JSON_ChallengeCategoryParam[] ChallengeCategory;
    public JSON_TrophyParam[] Trophy;
    public JSON_TrophyParam[] Challenge;
    public JSON_UnlockParam[] Unlock;
    public JSON_VipParam[] Vip;
    public JSON_ArenaWinResult[] ArenaWinResult;
    public JSON_ArenaResult[] ArenaRankResult;
    public JSON_StreamingMovie[] Mov;
    public JSON_BannerParam[] Banner;
    public JSON_QuestClearUnlockUnitDataParam[] QuestClearUnlockUnitData;
    public JSON_AwardParam[] Award;
    public JSON_LoginInfoParam[] LoginInfo;
    public JSON_CollaboSkillParam[] CollaboSkill;
    public JSON_TrickParam[] Trick;
    public JSON_BreakObjParam[] BreakObj;
    public JSON_VersusMatchingParam[] VersusMatchKey;
    public JSON_VersusMatchCondParam[] VersusMatchCond;
    public JSON_TowerScore[] TowerScore;
    public int[] TowerRank;
    public int[] MultilimitUnitLv;
    public JSON_FriendPresentItemParam[] FriendPresentItem;
    public JSON_WeatherParam[] Weather;
    public JSON_UnitUnlockTimeParam[] UnitUnlockTime;
    public JSON_TobiraParam[] Tobira;
    public JSON_TobiraCategoriesParam[] TobiraCategories;
    public JSON_TobiraCondsParam[] TobiraConds;
    public JSON_TobiraCondsUnitParam[] TobiraCondsUnit;
    public JSON_TobiraRecipeParam[] TobiraRecipe;
    public JSON_ConceptCardParam[] ConceptCard;
    public int[] ConceptCardLvTbl1;
    public int[] ConceptCardLvTbl2;
    public int[] ConceptCardLvTbl3;
    public int[] ConceptCardLvTbl4;
    public int[] ConceptCardLvTbl5;
    public int[] ConceptCardLvTbl6;
    public JSON_ConceptCardConditionsParam[] ConceptCardConditions;
    public JSON_ConceptCardTrustRewardParam[] ConceptCardTrustReward;
    public JSON_UnitGroupParam[] UnitGroup;
    public JSON_JobGroupParam[] JobGroup;
    public JSON_StatusCoefficientParam[] StatusCoefficient;
    public JSON_CustomTargetParam[] CustomTarget;
    public JSON_SkillAbilityDeriveParam[] SkillAbilityDerive;
    public JSON_RaidPeriodParam[] RaidPeriod;
    public JSON_RaidAreaParam[] RaidArea;
    public JSON_RaidBossParam[] RaidBoss;
    public JSON_RaidBattleRewardParam[] RaidBattleReward;
    public JSON_RaidBeatRewardParam[] RaidBeatReward;
    public JSON_RaidDamageRatioRewardParam[] RaidDamageRatioReward;
    public JSON_RaidAreaClearRewardParam[] RaidAreaClearReward;
    public JSON_RaidCompleteRewardParam[] RaidCompleteReward;
    public JSON_RaidRewardParam[] RaidReward;
    public JSON_TipsParam[] Tips;
    public JSON_GuildEmblemParam[] GuildEmblem;
    public JSON_GuildFacilityParam[] GuildFacility;
    public JSON_GuildFacilityLvParam[] GuildFacilityLvTbl;
    public JSON_ConvertUnitPieceExcludeParam[] ConvertUnitPieceExclude;
    public JSON_PremiumParam[] Premium;
    public JSON_DynamicTransformUnitParam[] DynamicTransformUnit;
    public JSON_RecommendedArtifactParam[] RecommendedArtifact;
    public JSON_SkillMotionParam[] SkillMotion;
    public JSON_DependStateSpcEffParam[] DependStateSpcEff;
    public JSON_InspSkillParam[] InspirationSkill;
    public JSON_InspSkillTriggerParam[] InspSkillTrigger;
    public JSON_InspSkillCostParam[] InspSkillOpenCost;
    public JSON_InspSkillCostParam[] InspSkillResetCost;
    public JSON_InspSkillLvUpCostParam[] InspSkillLvUpCost;
    public JSON_HighlightParam[] Highlight;
    public JSON_HighlightGift[] HighlightGift;
    public JSON_GenesisParam[] Genesis;
    public JSON_InitPlayer[] InitPlayer;
    public JSON_InitUnit[] InitUnit;
    public JSON_InitItem[] InitItem;
  }
}
