// Decompiled with JetBrains decompiler
// Type: SelectWorld
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: E2D362ED-2CBE-44F0-8985-22128799036A
// Assembly location: D:\User\Desktop\Assembly-CSharp.dll

using UnityEngine;
using UnityEngine.UI;

[AddComponentMenu("UI/Drafts/SelectWorld")]
public class SelectWorld : UIDraft
{
  [UIDraft.AutoGenerated]
  public Button World_Item;
  [UIDraft.AutoGenerated]
  public Text Text_WorldName;
  [UIDraft.AutoGenerated]
  public Text Text_MenuTitle;
  [UIDraft.AutoGenerated]
  public Button Btn_Decide;
}
