// Decompiled with JetBrains decompiler
// Type: SelectArea
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: E2D362ED-2CBE-44F0-8985-22128799036A
// Assembly location: D:\User\Desktop\Assembly-CSharp.dll

using UnityEngine;
using UnityEngine.UI;

[AddComponentMenu("UI/Drafts/SelectArea")]
public class SelectArea : UIDraft
{
  [UIDraft.AutoGenerated]
  public Text Text_AreaName;
  [UIDraft.AutoGenerated]
  public Text Text_MenuTitle;
  [UIDraft.AutoGenerated]
  public Button Area_Item;
  [UIDraft.AutoGenerated]
  public Button Btn_Decide;
  [UIDraft.AutoGenerated]
  public Button Btn_BackWorld;
}
