// Decompiled with JetBrains decompiler
// Type: Title
// Assembly: Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: E2D362ED-2CBE-44F0-8985-22128799036A
// Assembly location: D:\User\Desktop\Assembly-CSharp.dll

using UnityEngine;
using UnityEngine.UI;

[AddComponentMenu("UI/Drafts/Title")]
public class Title : UIDraft
{
  [UIDraft.AutoGenerated]
  public Button Button_TapStart;
  [UIDraft.AutoGenerated]
  public Button Button_NewGame;
}
